# Generated by Django 3.2.25 on 2025-11-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('publishing_date', models.DateField()),
                ('distribution_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.bookcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='books_book_categor_bb0287_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publishing_date'], name='books_book_publish_4b64c4_idx'),
        ),
    ]
