# Generated by Django 3.2.25 on 2025-11-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_book_authors'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_publish_4b64c4_idx',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishing_date',
            new_name='published_date',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['published_date'], name='books_book_publish_649cd8_idx'),
        ),
    ]
